import type { NextPage } from "next";
import Head from "next/head";
import NewsList from "../components/NewsList";
import NavBar from "../components/NavBar";
import { Container } from "@material-ui/core";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>News App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <NavBar />
        <Container maxWidth="lg">
          <NewsList />
        </Container>
      </main>
    </div>
  );
};

export default Home;
